project:
  type: book
  output-dir: docs

book:
  title: "International Master of Environmental Sciences"
  subtitle: "Module Handbook"
  author: "IMES Examination Committee"
  date: today
  reader-mode: true
  downloads: pdf
  chapters:
    - index.qmd
    - part: "DESCRIPTION OF THE PROGRAM"
      chapters:
        - intro.qmd
    - part: "MODULE DESCRIPTIONS"
      chapters: 
        - am-geosphere-and-hydrosphere.qmd
        - am-sustainable-development.qmd
        - am-law.qmd
        - am-ecosystems-and-landscape.qmd
        - sm-internship.qmd
        - master-thesis.qmd
    - part: "EXAMPLE SCHEDULES"
      chapters: 
        - schedules.qmd
  page-footer:
    right: |
      This module handbook was built with <a href="https://quarto.org/">Quarto</a>.
  sidebar: 
    logo: "images/Universitaet zu Koeln Logo ENG.png"


bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, scss/ims-style.scss]
    # include-in-header:
    #   text: |
    #     <script>
    #       document.addEventListener("DOMContentLoaded", function() {
    #         var sidebar = document.getElementById('quarto-sidebar');
    #         var logo = sidebar.getElementsByTagName('img')[0].cloneNode();
    #         
    #         sidebar.appendChild(logo);
    #       });
    #     </script>
    code-link: true
    mainfont: Atkinson Hyperlegible
    monofont: Source Code Pro
    author-meta: "IMES Examination Committee"
    lightbox: 
      match: auto
      loop: false
    fig-dpi: 300
    fig-show: hold
    fig-align: center
  pdf:
    include-in-header: latex/ims-style.tex
    #include-after-body: latex/after-body.tex
    documentclass: book
    classoption:
        - 10pt
        - openany
    pdf-engine: pdflatex
    biblio-style: apalike
    keep-tex: true
    block-headings: false
    top-level-division: chapter
    fig-dpi: 300
    fig-show: hold
    fig-pos: H
    tbl-pos: H
    fig-align: center
    toc: true
    toc-depth: 1


website: 
  announcement: 
    icon: cone-striped
    dissmissalbe: true
    content: |
      "You are reading the work-in-progress of the module handbook for the IMES program. The modules and their discriptions are subject to changes."
    type: primary
    position: below-navbar
