# Sustainable Development {.unnumbered}

| | |
|----|---|
| **Type of Module** | Advanced Module |
| **Module Code** | IMES-AM-SD |
| **Workload** | 180 h |
| **ECTS** | 6 |
| **Term** | Semester |
| **Offered Every** | WiSe |
| **Start** | WiSe |
| **Duration** | 1 semester |
: {.striped .hover .bordered .sm}

| Course Types | Contact Time | Self-study Time | 
|--------------|--------------|-----------------|
| a) Seminar: Sustainable Development | 2 SWS / 30 h | 60 h |
| b) Practical: Fieldwork | 2 SWS / 30 h | 60 h |
: {.info .bordered}

## Module Description

This module consists of two courses: a literature-based seminar in Sustainable Development and Fieldwork. It provides an in-depth exploration of the principles, challenges, and frameworks of sustainability. Key topics include the Sustainable Development Goals (SDGs), climate change, planetary boundaries, loss of biodiversity and Education for Sustainable Action (ESA) as a tool for transformative action. The course addresses critical global issues such as inequality, urbanization, and environmental degradation, emphasizing their interconnections and linking them to actionable strategies for sustainable solutions.

## Module Objectives

- Explore the foundational concepts of sustainable development, including its pillars, challenges, and global frameworks like Agenda 21 and the SDGs.
- Analyse further important concepts like planetary boundaries, climate change and loss of biodiversity, based on scientific literature.
- Examine the role of Education for Sustainable Action (ESA) in promoting transformative learning, systems thinking, and sustainability action.

## Module Outcomes

- Understand the foundational principles of sustainable development, including its pillars, challenges, and key global frameworks such as Agenda 21 and the SDGs.
- Analyze complex concepts like planetary boundaries, climate change, and biodiversity loss by critically engaging with scientific literature.
- Evaluate the challenges and opportunities in achieving sustainable development in the context of global and local issues.
- Examine the role of Education for Sustainable Development (ESD) in fostering transformative learning, systems thinking, and actionable strategies.
- Develop practical skills in applying systems thinking to identify and address sustainability challenges during Field Work.

## Module Content

### a) Seminar: Sustainable Development

- Basic concepts of sustainable development:
  - Understanding ‘sustainability’ and ‘development’
  - Causes and effects of unsustainable development like consumerism, globalization, urbanization, ecosystem degradation, inequity
  - Pillars of sustainable development: economic, social, environmental, political (governance)
  - Timeline of sustainable development; Agenda 21; Millennium development goals and sustainable development goals.
  - ESD as a tool for transformative learning and systems thinking
- Key sustainability concepts and challenges:
  - Climate change: causes, impacts, and mitigation strategies
  - Planetary boundaries and their relevance to sustainability
  - Ecosystem services and their role in sustainable development
  - Rapid population growth and food security
  - Poverty, income inequality, and gender disparity
  - Urbanization and its challenges, including energy transformation
  - Environmental degradation and loss of biodiversity

### b) Practical: Fieldwork

- Visit and analysis of sustainability projects.
- Developing a matrix for analysing sustainability projects along with indicators.

## Teaching Methods

Literature-based seminar and practical

## Prerequisites

None

## Type of Examination

Portfolio based on a) and b), 5 to 10 pages.

## Credits Awarded

Credit points are awarded upon regular and active participation, as well as the successful completion of the module's examination with a minimum passing grade of 4.0. (sufficient).

## Compatibility with Other Curricula

JIMES (JIMES-AM-SDUoC), M.Sc. Module part (a) in Geography (AM1 and AM2), MA Geography (AM1 and AM2) and MEd Geography (AM1)

## Proportion of Final Grade

5%

## Module Coordinator

Dr. Veronika Selbach and Dr. Verena Dlugoß (Institute of Geography)

## Further Information

Restrictions on the number of places available for IMES students might apply.
